name: Daily Email Notifications

on:
  schedule:
    - cron: "30 2 * * *"   # Runs at 8:00 AM IST (2:30 UTC)
    - cron: "30 12 * * *"  # Runs at 6:00 PM IST (12:30 UTC)
  workflow_dispatch:

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Daily Email Script
        env:
          MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
          MYSQL_PORT: ${{ secrets.MYSQL_PORT }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          AIVEN_CA_PEM: ${{ secrets.AIVEN_CA_PEM }}
          SENDER_NAME: ${{ secrets.SENDER_NAME }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          API: ${{ secrets.API }}
        run: python daily_email.py
